package bit.project.server;

import bit.project.server.util.security.SystemModule;

public enum UsecaseList{
    @SystemModule("User") SHOW_ALL_USERS(1),
    @SystemModule("User") SHOW_USER_DETAILS(2),
    @SystemModule("User") ADD_USER(3),
    @SystemModule("User") UPDATE_USER(4),
    @SystemModule("User") DELETE_USER(5),
    @SystemModule("User") RESET_USER_PASSWORDS(6),
    @SystemModule("Role") SHOW_ALL_ROLES(7),
    @SystemModule("Role") SHOW_ROLE_DETAILS(8),
    @SystemModule("Role") ADD_ROLE(9),
    @SystemModule("Role") UPDATE_ROLE(10),
    @SystemModule("Role") DELETE_ROLE(11),
    @SystemModule("Cls") SHOW_ALL_CLSES(12),
    @SystemModule("Cls") SHOW_CLS_DETAILS(13),
    @SystemModule("Cls") ADD_CLS(14),
    @SystemModule("Cls") UPDATE_CLS(15),
    @SystemModule("Cls") DELETE_CLS(16),
    @SystemModule("Clssession") SHOW_ALL_CLSSESSIONS(17),
    @SystemModule("Clssession") SHOW_CLSSESSION_DETAILS(18),
    @SystemModule("Clssession") ADD_CLSSESSION(19),
    @SystemModule("Clssession") UPDATE_CLSSESSION(20),
    @SystemModule("Clssession") DELETE_CLSSESSION(21),
    @SystemModule("Discount") SHOW_ALL_DISCOUNTS(22),
    @SystemModule("Discount") SHOW_DISCOUNT_DETAILS(23),
    @SystemModule("Discount") ADD_DISCOUNT(24),
    @SystemModule("Discount") UPDATE_DISCOUNT(25),
    @SystemModule("Discount") DELETE_DISCOUNT(26),
    @SystemModule("Employee") SHOW_ALL_EMPLOYEES(27),
    @SystemModule("Employee") SHOW_EMPLOYEE_DETAILS(28),
    @SystemModule("Employee") ADD_EMPLOYEE(29),
    @SystemModule("Employee") UPDATE_EMPLOYEE(30),
    @SystemModule("Employee") DELETE_EMPLOYEE(31),
    @SystemModule("Enrollment") SHOW_ALL_ENROLLMENTS(32),
    @SystemModule("Enrollment") SHOW_ENROLLMENT_DETAILS(33),
    @SystemModule("Enrollment") ADD_ENROLLMENT(34),
    @SystemModule("Enrollment") UPDATE_ENROLLMENT(35),
    @SystemModule("Enrollment") DELETE_ENROLLMENT(36),
    @SystemModule("Exam") SHOW_ALL_EXAMS(37),
    @SystemModule("Exam") SHOW_EXAM_DETAILS(38),
    @SystemModule("Exam") ADD_EXAM(39),
    @SystemModule("Exam") UPDATE_EXAM(40),
    @SystemModule("Exam") DELETE_EXAM(41),
    @SystemModule("Examresult") SHOW_ALL_EXAMRESULTS(42),
    @SystemModule("Examresult") SHOW_EXAMRESULT_DETAILS(43),
    @SystemModule("Examresult") ADD_EXAMRESULT(44),
    @SystemModule("Examresult") UPDATE_EXAMRESULT(45),
    @SystemModule("Examresult") DELETE_EXAMRESULT(46),
    @SystemModule("Gradeyear") SHOW_ALL_GRADEYEARS(47),
    @SystemModule("Gradeyear") SHOW_GRADEYEAR_DETAILS(48),
    @SystemModule("Gradeyear") ADD_GRADEYEAR(49),
    @SystemModule("Gradeyear") UPDATE_GRADEYEAR(50),
    @SystemModule("Gradeyear") DELETE_GRADEYEAR(51),
    @SystemModule("Guardian") SHOW_ALL_GUARDIANS(52),
    @SystemModule("Guardian") SHOW_GUARDIAN_DETAILS(53),
    @SystemModule("Guardian") ADD_GUARDIAN(54),
    @SystemModule("Guardian") UPDATE_GUARDIAN(55),
    @SystemModule("Guardian") DELETE_GUARDIAN(56),
    @SystemModule("Lesson") SHOW_ALL_LESSONS(57),
    @SystemModule("Lesson") SHOW_LESSON_DETAILS(58),
    @SystemModule("Lesson") ADD_LESSON(59),
    @SystemModule("Lesson") UPDATE_LESSON(60),
    @SystemModule("Lesson") DELETE_LESSON(61),
    @SystemModule("Material") SHOW_ALL_MATERIALS(62),
    @SystemModule("Material") SHOW_MATERIAL_DETAILS(63),
    @SystemModule("Material") ADD_MATERIAL(64),
    @SystemModule("Material") UPDATE_MATERIAL(65),
    @SystemModule("Material") DELETE_MATERIAL(66),
    @SystemModule("Materialissue") SHOW_ALL_MATERIALISSUES(67),
    @SystemModule("Materialissue") SHOW_MATERIALISSUE_DETAILS(68),
    @SystemModule("Materialissue") ADD_MATERIALISSUE(69),
    @SystemModule("Materialissue") UPDATE_MATERIALISSUE(70),
    @SystemModule("Materialissue") DELETE_MATERIALISSUE(71),
    @SystemModule("Sheduledate") SHOW_ALL_SHEDULEDATES(72),
    @SystemModule("Sheduledate") SHOW_SHEDULEDATE_DETAILS(73),
    @SystemModule("Sheduledate") ADD_SHEDULEDATE(74),
    @SystemModule("Sheduledate") UPDATE_SHEDULEDATE(75),
    @SystemModule("Sheduledate") DELETE_SHEDULEDATE(76),
    @SystemModule("Student") SHOW_ALL_STUDENTS(77),
    @SystemModule("Student") SHOW_STUDENT_DETAILS(78),
    @SystemModule("Student") ADD_STUDENT(79),
    @SystemModule("Student") UPDATE_STUDENT(80),
    @SystemModule("Student") DELETE_STUDENT(81),
    @SystemModule("Studentattendance") SHOW_ALL_STUDENTATTENDANCES(82),
    @SystemModule("Studentattendance") SHOW_STUDENTATTENDANCE_DETAILS(83),
    @SystemModule("Studentattendance") ADD_STUDENTATTENDANCE(84),
    @SystemModule("Studentattendance") UPDATE_STUDENTATTENDANCE(85),
    @SystemModule("Studentattendance") DELETE_STUDENTATTENDANCE(86),
    @SystemModule("Studentpayment") SHOW_ALL_STUDENTPAYMENTS(87),
    @SystemModule("Studentpayment") SHOW_STUDENTPAYMENT_DETAILS(88),
    @SystemModule("Studentpayment") ADD_STUDENTPAYMENT(89),
    @SystemModule("Studentpayment") UPDATE_STUDENTPAYMENT(90),
    @SystemModule("Studentpayment") DELETE_STUDENTPAYMENT(91),
    @SystemModule("Subject") SHOW_ALL_SUBJECTS(92),
    @SystemModule("Subject") SHOW_SUBJECT_DETAILS(93),
    @SystemModule("Subject") ADD_SUBJECT(94),
    @SystemModule("Subject") UPDATE_SUBJECT(95),
    @SystemModule("Subject") DELETE_SUBJECT(96),
    @SystemModule("Timetable") SHOW_ALL_TIMETABLES(97),
    @SystemModule("Timetable") SHOW_TIMETABLE_DETAILS(98),
    @SystemModule("Timetable") ADD_TIMETABLE(99),
    @SystemModule("Timetable") UPDATE_TIMETABLE(100),
    @SystemModule("Timetable") DELETE_TIMETABLE(101),
    @SystemModule("Report") Show_All_Reports(102);

    public static final UsecaseList SHOW_YEAR_WISE_EMPLOYEE_COUNT = null;
    public static final UsecaseList SHOW_YEAR_WISE_STUDENT_COUNT = null;
    public final int value;

    UsecaseList(int value){
        this.value = value;
    }

}
